### ISSUE TITLE
Changed Lines

### ISSUE THREAD

**Issue by nightznero** [ArtikusHG/Mull-OLEDDark#3]
Helloz!

I have a question,could You please share which lines/Hashtag names/colors has been changed by ur code?

Best Regards, NIGHTZNERO.

**Comment by ArtikusHG** [comment]
it's pretty obvious if you read the script, but im changing fx_mobile_layer_color_1 and fx_mobile_layer_color_2 in res/values-night/colors.xml

**Comment by nightznero** [comment]
> it's pretty obvious if you read the script, but im changing fx_mobile_layer_color_1 and fx_mobile_layer_color_2 in res/values-night/colors.xml

Too little to late cuz Mull is RIP but if IronFox is 1:1;
03D4 (photonDarkGrey60)
03CF (photonDarkGrey30)
03D0 (photonDarkGrey30A95)
Gives the same results,after changing it to black and then use ur lines it's doesn't change/add anything more "black". Just in case if u are interested.

Trying also change background of tab list but cannot find correct color inside code (#2B2A33) must be some blur added or so
