### ISSUE TITLE
Changing other components dark

### ISSUE THREAD

**Issue by GoodyOG** [ArtikusHG/Mull-OLEDDark#4]
![Screenshot_20241204-014355_Iceraven](https://github.com/user-attachments/assets/b9b78f69-9d05-4bc8-a61a-dddcebd4bb23)
will it be possible to change the tab switcher to oled/dark black?

**Comment by ArtikusHG** [comment]
the messed this up really badly for some reason, ive been working on this for a few hours and i have no clue why nothing works. will keep trying though

**Comment by ArtikusHG** [comment]
i wont be fixing this because nothing ive tried works and i dont have time to mess with this, if anyone has an idea how to do it you're welcome

**Comment by GoodyOG** [comment]
Yeah, I also spent hours trying to do it for Iceraven but nothing was working, pissed me up so badly, lol.
